---
- name: Launch job to fetch URLs for open data
  command: >
    {{ projectdir }}/venv/bin/python
    data.py
    fetch
    resource_links
    --db postgres
    --db-config {{ src }}/{{ postgres_config }}
    chdir={{ src }}
  async: "{{ long_time }}"
  poll: 0
  register: fetcher_sleeper

- name: Fail if job already exited.  If failure, this job may already be running.
  async_status: jid={{ fetcher_sleeper.ansible_job_id }}
  register: job_result
  failed_when: job_result.finished
  retries: 1
